/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SoulsRouteImport } from './app/souls'
import { Route as SessionsRouteImport } from './app/sessions'
import { Route as SearxngRouteImport } from './app/searxng'
import { Route as PossessRouteImport } from './app/possess'
import { Route as ModelsRouteImport } from './app/models'
import { Route as KnowledgeRouteImport } from './app/knowledge'
import { Route as AnalyticsRouteImport } from './app/analytics'
import { Route as IndexRouteImport } from './app/index'
import { Route as SoulsRefineRouteImport } from './app/souls.refine'
import { Route as SoulsCollectRouteImport } from './app/souls.collect'
import { Route as SoulsNameRouteImport } from './app/souls.$name'
import { Route as SessionsIdRouteImport } from './app/sessions.$id'
import { Route as PossessSessionIdRouteImport } from './app/possess.$sessionId'

const SoulsRoute = SoulsRouteImport.update({
  id: '/souls',
  path: '/souls',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearxngRoute = SearxngRouteImport.update({
  id: '/searxng',
  path: '/searxng',
  getParentRoute: () => rootRouteImport,
} as any)
const PossessRoute = PossessRouteImport.update({
  id: '/possess',
  path: '/possess',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsRefineRoute = SoulsRefineRouteImport.update({
  id: '/refine',
  path: '/refine',
  getParentRoute: () => SoulsRoute,
} as any)
const SoulsCollectRoute = SoulsCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => SoulsRoute,
} as any)
const SoulsNameRoute = SoulsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => SoulsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const PossessSessionIdRoute = PossessSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => PossessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/knowledge': typeof KnowledgeRoute
  '/models': typeof ModelsRoute
  '/possess': typeof PossessRouteWithChildren
  '/searxng': typeof SearxngRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/souls': typeof SoulsRouteWithChildren
  '/possess/$sessionId': typeof PossessSessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/souls/$name': typeof SoulsNameRoute
  '/souls/collect': typeof SoulsCollectRoute
  '/souls/refine': typeof SoulsRefineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/knowledge': typeof KnowledgeRoute
  '/models': typeof ModelsRoute
  '/possess': typeof PossessRouteWithChildren
  '/searxng': typeof SearxngRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/souls': typeof SoulsRouteWithChildren
  '/possess/$sessionId': typeof PossessSessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/souls/$name': typeof SoulsNameRoute
  '/souls/collect': typeof SoulsCollectRoute
  '/souls/refine': typeof SoulsRefineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/knowledge': typeof KnowledgeRoute
  '/models': typeof ModelsRoute
  '/possess': typeof PossessRouteWithChildren
  '/searxng': typeof SearxngRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/souls': typeof SoulsRouteWithChildren
  '/possess/$sessionId': typeof PossessSessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/souls/$name': typeof SoulsNameRoute
  '/souls/collect': typeof SoulsCollectRoute
  '/souls/refine': typeof SoulsRefineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/knowledge'
    | '/models'
    | '/possess'
    | '/searxng'
    | '/sessions'
    | '/souls'
    | '/possess/$sessionId'
    | '/sessions/$id'
    | '/souls/$name'
    | '/souls/collect'
    | '/souls/refine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/knowledge'
    | '/models'
    | '/possess'
    | '/searxng'
    | '/sessions'
    | '/souls'
    | '/possess/$sessionId'
    | '/sessions/$id'
    | '/souls/$name'
    | '/souls/collect'
    | '/souls/refine'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/knowledge'
    | '/models'
    | '/possess'
    | '/searxng'
    | '/sessions'
    | '/souls'
    | '/possess/$sessionId'
    | '/sessions/$id'
    | '/souls/$name'
    | '/souls/collect'
    | '/souls/refine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  ModelsRoute: typeof ModelsRoute
  PossessRoute: typeof PossessRouteWithChildren
  SearxngRoute: typeof SearxngRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SoulsRoute: typeof SoulsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/souls': {
      id: '/souls'
      path: '/souls'
      fullPath: '/souls'
      preLoaderRoute: typeof SoulsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searxng': {
      id: '/searxng'
      path: '/searxng'
      fullPath: '/searxng'
      preLoaderRoute: typeof SearxngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/possess': {
      id: '/possess'
      path: '/possess'
      fullPath: '/possess'
      preLoaderRoute: typeof PossessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/refine': {
      id: '/souls/refine'
      path: '/refine'
      fullPath: '/souls/refine'
      preLoaderRoute: typeof SoulsRefineRouteImport
      parentRoute: typeof SoulsRoute
    }
    '/souls/collect': {
      id: '/souls/collect'
      path: '/collect'
      fullPath: '/souls/collect'
      preLoaderRoute: typeof SoulsCollectRouteImport
      parentRoute: typeof SoulsRoute
    }
    '/souls/$name': {
      id: '/souls/$name'
      path: '/$name'
      fullPath: '/souls/$name'
      preLoaderRoute: typeof SoulsNameRouteImport
      parentRoute: typeof SoulsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/possess/$sessionId': {
      id: '/possess/$sessionId'
      path: '/$sessionId'
      fullPath: '/possess/$sessionId'
      preLoaderRoute: typeof PossessSessionIdRouteImport
      parentRoute: typeof PossessRoute
    }
  }
}

interface PossessRouteChildren {
  PossessSessionIdRoute: typeof PossessSessionIdRoute
}

const PossessRouteChildren: PossessRouteChildren = {
  PossessSessionIdRoute: PossessSessionIdRoute,
}

const PossessRouteWithChildren =
  PossessRoute._addFileChildren(PossessRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface SoulsRouteChildren {
  SoulsNameRoute: typeof SoulsNameRoute
  SoulsCollectRoute: typeof SoulsCollectRoute
  SoulsRefineRoute: typeof SoulsRefineRoute
}

const SoulsRouteChildren: SoulsRouteChildren = {
  SoulsNameRoute: SoulsNameRoute,
  SoulsCollectRoute: SoulsCollectRoute,
  SoulsRefineRoute: SoulsRefineRoute,
}

const SoulsRouteWithChildren = SoulsRoute._addFileChildren(SoulsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  KnowledgeRoute: KnowledgeRoute,
  ModelsRoute: ModelsRoute,
  PossessRoute: PossessRouteWithChildren,
  SearxngRoute: SearxngRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SoulsRoute: SoulsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
